### ISSUE TITLE
Trigger by swipe left from screen. Will it have option to disable/enable?

### ISSUE THREAD

**Issue by aillez** [zhougy0717/Niwatori#7]
Since I already use some gesture to trigger it. Will this option available in a later version?

Best regards,
Watcharin L.

**Comment by zhougy0717** [comment]
I add this feature is because fooview refuses to work after upgrade,
although gravitybox still works. I guess there is a bug in fooview. So I
want to make Niwatori work independently. Then I add this. I don't add
switch for enable and disable. I can add it in future version if it's
desired.

**Comment by aillez** [comment]
Ok, just a thought. If it available in the next version it's great but if not it's still ok for me.
:+1:

**Comment by zhougy0717** [comment]
Fix it in 0.6.3

**Comment by aillez** [comment]
Already updated latest version since it came out.

Thank you so much.
